# ==========================================
# DevFlow Application
# ==========================================

spring.application.name=DevFlow

# Server
server.port=8080

# ==========================================
# JSON
# ==========================================

#spring.jackson.serialization.write-dates-as-timestamps=false

# ==========================================
# Logging
# ==========================================

logging.level.root=INFO
logging.level.com.devflow=DEBUG