spring.application.name=E-Learning

#Database or DataSource configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=sb13usr
spring.datasource.password=qwerty

spring.datasource.url=jdbc:postgresql://localhost:1500/learning_db

#JPA configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


